- hosts: test_boxes
  gather_facts: false
  tasks:
  - name: stop AWS instances
    local_action:
      module: ec2
      state: 'stopped'
      region: us-east-1
      instance_ids: "{{ hostvars[inventory_hostname]['ec2_id'] }}"