- hosts: tag_type_gig_qa_geoserver
  gather_facts: True
  remote_user: ec2-user
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: linux_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: terminate geoserver instance
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: tag_type_gig_qa_jmeter
  gather_facts: True
  remote_user: ec2-user
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: linux_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"
    - name: terminate jmeter instance
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: test_boxes
  gather_facts: false
  tasks:
  - name: terminate jmeter,geoserver, & rds instance
    local_action:
      module: ec2
      state: 'absent'
      region: us-east-1
      instance_ids: "{{ hostvars[inventory_hostname]['ec2_id'] }}"
  - name: terminate rds instance
    rds:
      command: delete
      instance_name: gig-qa-rds
      