- name: install java
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: true

- name: uninstall java 1.7
  yum:
    name: java-1.7.0-openjdk
    state: absent
  become: true
  
### install jmeter
- name: install jmeter
  unarchive:
    src: http://httpd-mirror.frgl.pw/apache//jmeter/binaries/apache-jmeter-3.1.tgz
    dest: /opt/
    remote_src: true

- name: add jmeter to PATH
  lineinfile:
    dest=/home/ec2-user/.bash_profile
    state=present
    backrefs=no
    regexp="export PATH"
    line="export PATH=$PATH{{':'}}/opt/apache-jmeter-3.1/bin"
 
### pull test suite from git given repo & branch


### run jmeter play (runs the tests)