- name: install java
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: true

- name: uninstall java 1.7
  yum:
    name: java-1.7.0-openjdk
    state: absent
  become: true
  
### install jmeter
- name: install jmeter
  unarchive:
    src: http://httpd-mirror.frgl.pw/apache//jmeter/binaries/apache-jmeter-3.1.tgz
    dest: /opt/
    remote_src: true

- name: add jmeter to PATH
  lineinfile:
    dest=/home/ec2-user/.bash_profile
    state=present
    backrefs=no
    regexp="export PATH"
    line="export PATH=$PATH{{':'}}/opt/apache-jmeter-3.1/bin"
 
- name: make tests dir
  file: 
    path: /home/ec2-user/jmeter_tests
    state: directory
    mode: 0700
    
- name: make results dir
  file:
    path: /home/ec2-user/jmeter_tests/results
    state: directory
    mode: 0666
    
- name: copy jmeter tests
  unarchive: 
    src: jmeter_tests.zip
    dest: /home/ec2-user/jmeter_tests
    mode: 0777
    
- name: copy bboxes
  unarchive:
    src: bboxes.zip
    dest: /home/ec2-user/jmeter_tests
    
- name: copy test runner script
  copy:
    src: run_jmeter.sh
    dest: /home/ec2-user
    mode: 0777

### run the tests