### install java and maven
- name: install java
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
  become: true

- name: uninstall java 1.7
  yum:
    name: java-1.7.0-openjdk
    state: absent
  become: true
    
- name: install git
  yum:
    name: git
    state: present
  become: true
  
- name: install tomcat8
  unarchive:
    src: "http://mirror.its.dal.ca/apache/tomcat/tomcat-8/v8.5.11/bin/apache-tomcat-8.5.11.zip"
    dest: /opt
    remote_src: yes
  become: true
    
- name: rename tomcat folder
  command: mv /opt/apache-tomcat-8.5.11 /opt/apache-tomcat
  args:
    creates: /opt/apache-tomcat
  become: true

- name: copy tomatcat env file
  copy:
    src: setenv.sh
    dest: /opt/apache-tomcat/bin/
  become: true

- name: install maven
  unarchive:
    src: http://apache.parentingamerica.com/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    dest: /opt
    remote_src: yes
  become: true
    
- name: rename maven folder
  command: mv /opt/apache-maven-"{{ maven_version }}" /opt/apache-maven
  args:
    creates: /opt/apache-maven
  become: true

### build geogig from git repo and branch name
- name: Pull geogig from git
  git:
    repo: https://github.com/locationtech/geogig.git
    dest: /home/ec2-user/geogig
    version: "{{ geogig_branch }}"
    
### get geoserver
- name: Pull geoserver from git
  git:
    repo: https://github.com/geoserver/geoserver.git
    dest: /home/ec2-user/geoserver
    version: "{{ geoserver_branch }}"
    
- name: copy maven build script
  copy:
    src: mavenBuild.sh
    dest: /home/ec2-user/
    mode: "u+rwx"
    
- name: run build
  shell: ./mavenBuild.sh

- name: make temp war dir
  file:
    path: /home/ec2-user/geoserver_war
    state: directory
#     
- name: make war dir in tomcat
  file:
    path: /opt/apache-tomcat/webapps/geoserver
    state: directory
  become: true
# 
- name: unzip war
  shell: unzip -o /home/ec2-user/geoserver/src/web/app/target/geoserver.war -d /home/ec2-user/geoserver_war
  become: true
#   
  #can't recursively copy directories with remote_src
- name: copy war to tomcat
  shell: sudo cp -fr /home/ec2-user/geoserver_war/* /opt/apache-tomcat/webapps/geoserver
#   
- name: install marlin
  get_url:
    url: https://github.com/bourgesl/marlin-renderer/releases/download/v0.7.5_2/marlin-0.7.5-Unsafe.jar
    dest: /home/ec2-user
  become: true
  
- name: copy marlin to tomcat
  copy: 
    src: /home/ec2-user/marlin-0.7.5-Unsafe.jar
    dest: /opt/apache-tomcat/webapps/geoserver/WEB-INF/lib
    remote_src: yes
  become: true
    
- name: create data dir
  file:
    path: /var/opt/geoserver/data
    state: directory
    mode: 0777
    owner: ec2-user
  become: true
    
- name: copy tomcat settings
  copy: 
    src: setenv.sh
    dest: /opt/apache-tomcat/bin
    mode: 0600
  become: true
    
- name: make bin dir executable
  shell: sudo chmod -R 777 /opt/apache-tomcat/bin/*.sh
  
- name: make logs rw
  shell: sudo chmod -R 644 /opt/apache-tomcat/logs
  
- name: start geoserver
  command: ./startup.sh
  args:
    chdir: /opt/apache-tomcat/bin
  become: true
     
# - name: setup geogig, call geogig play
