### install java and maven
- name: install java
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
  become: true

- name: uninstall java 1.7
  yum:
    name: java-1.7.0-openjdk
    state: absent
  become: true
    
- name: install git
  yum:
    name: git
    state: present
  become: true
  
- name: install curl
  yum:
    name: curl
    state: present
  become: true
 
- name: install tomcat8
  yum:
    name: tomcat8
    state: present
  become: true
  
- name: copy tomatcat conf file
  copy:
    src: tomcat8.conf
    dest: /usr/share/tomcat8/conf
    group: tomcat
  become: true

- name: install maven
  unarchive:
    src: http://apache.parentingamerica.com/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    dest: /opt
    remote_src: yes
  become: true
    
- name: rename maven folder
  command: mv /opt/apache-maven-"{{ maven_version }}" /opt/apache-maven
  args:
    creates: /opt/apache-maven
  become: true

### build geogig from git repo and branch name
- name: Pull geogig from git
  git:
    repo: https://github.com/locationtech/geogig.git
    dest: /home/ec2-user/geogig
    version: "{{ geogig_branch }}"
    
### get geoserver
- name: Pull geoserver from git
  git:
    repo: https://github.com/geoserver/geoserver.git
    dest: /home/ec2-user/geoserver
    version: "{{ geoserver_version }}"
    
- name: copy maven build script
  copy:
    src: mavenBuild.sh
    dest: /home/ec2-user/
    mode: "u+rwx"
    
- name: run build
  shell: ./mavenBuild.sh

- name: clean temp war dir
  file:
    path: /home/ec2-user/geoserver_war
    state: absent
  become: true

- name: make temp war dir
  file:
    path: /home/ec2-user/geoserver_war
    state: directory

- name: make remove old geoserver dir in tomcat
  file:
    path: /usr/share/tomcat8/webapps/geoserver
    state: absent
  become: true
    
- name: make war dir in tomcat
  file:
    path: /usr/share/tomcat8/webapps/geoserver
    state: directory
  become: true
# 
- name: unzip war
  shell: unzip -o /home/ec2-user/geoserver/src/web/app/target/geoserver.war -d /home/ec2-user/geoserver_war
  become: true
#   
  #can't recursively copy directories with remote_src
- name: copy war to tomcat
  shell: sudo cp -fr /home/ec2-user/geoserver_war/* /usr/share/tomcat8/webapps/geoserver
#   
- name: install marlin
  get_url:
    url: https://github.com/bourgesl/marlin-renderer/releases/download/v0.7.5_2/marlin-0.7.5-Unsafe.jar
    dest: /home/ec2-user
  become: true
  
- name: copy marlin to tomcat
  copy: 
    src: /home/ec2-user/marlin-0.7.5-Unsafe.jar
    dest: /usr/share/tomcat8/webapps/geoserver/WEB-INF/lib
    remote_src: yes
  become: true
    
- name: clean data dir
  file:
    path: /var/opt/geoserver/data
    state: absent
  become: true

- name: create data dir
  file:
    path: /var/opt/geoserver/data
    state: directory
    mode: 0777
    owner: ec2-user
  become: true
    
- name: start geoserver
  service:
    name: tomcat8
    state: restarted
  become: true
  
#setup geogig
- include: geogig.yml
